name: dragonflye-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - perl-digest-sha=5.88
  - fastp=0.23.1
  - filtlong=0.2.1
  - nanoq=0.9.0
  - prokka=1.14.5
  - quast=5.0.2
  - bandage=0.8.1
